#!/usr/bin/env bash
# Install and configure HAproxy on my lb-01 server

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
sudo sed -i "$ a\listen 12775-lb-01\n\tbind *:80\n\tmode http\n\tbalance roundrobin\n\toption httpclose\n\toption forwardfor\n\tserver 12775-web-02 3.234.252.177:80 check\n\tserver 12775-web-01 3.228.21.22:80 check" /etc/haproxy/haproxy.cfg
sudo service haproxy start
